format_version: 12

pipelines:
  HelloWorldPipeline:
    group: HelloWorldGroup
    materials:
      git:
        url: https://github.com/htetgit/Sample-repo.git
        branch: main
    stages:
      - name: Build
        jobs:
          - name: BuildAndRunJob
            tasks:
              - exec:
                  command: go
                  arguments:
                    - mod
                    - init
                    - hello-world-go
                  working_directory: src/hello-app
                  environment_variables:
                    GO111MODULE: "on"
              
              - exec:
                  command: go
                  arguments:
                    - get
                    - github.com/gorilla/mux
                  working_directory: src/hello-app
                  environment_variables:
                    GO111MODULE: "on"

              - exec:
                  command: go
                  arguments:
                    - mod
                    - tidy
                  working_directory: src/hello-app
                  environment_variables:
                    GO111MODULE: "on"
              
              - exec:
                  command: go
                  arguments:
                    - build
                    - -o
                    - main.exe
                    - .
                  working_directory: src/hello-app
                  environment_variables:
                    GO111MODULE: "on"
              
              - exec:
                  command: powershell
                  arguments:
                    - -Command
                    - |
                      .\main.exe
                      Start-Sleep -Seconds 10
                      $response = Invoke-WebRequest -Uri http://localhost:8080 -UseBasicParsing
                      if ($response.Content -eq "Hello, World!") {
                        Write-Output "Test Passed"
                      } else {
                        Write-Output "Test Failed"
                        exit 1
                      }
                  working_directory: src/hello-app
